wip

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -56,6 +56,33 @@ jobs:
       - run:
           name: Lint codebase
           command: npx --no-install eslint .
+  check_supported_versions:
+    executor: docker-publisher
+    steps:
+      - checkout
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - run:
+          name: Authenticate with cluster
+          command: |
+            echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./live_ca.crt
+            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./live_ca.crt --server=https://${K8S_CLUSTER_NAME}
+            kubectl config set-credentials circleci --token=${K8S_TOKEN_DEV}
+            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=claim-criminal-injuries-compensation-dev
+            kubectl config use-context ${K8S_CLUSTER_NAME}
+            kubectl config current-context
+            kubectl --namespace=claim-criminal-injuries-compensation-dev get pods
+      - run:
+          name: Trigger the cronjob
+          command: |
+            kubectl create job --from=cronjob/claim-criminal-injuries-dev-supported-versions version-check-$(date +%s)
+      - run:
+          name: Trigger the cronjob
+          command: |
+            JOB_NAME=$(kubectl get jobs --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1:].metadata.name}')
+            echo "Waiting for job $JOB_NAME to finish..."
+            kubectl wait --for=condition=complete --timeout=300s job/$JOB_NAME || \
+            (kubectl logs job/$JOB_NAME && echo "Job failed" && exit 1)
   build:
     executor: docker-publisher
     steps:
